name: Ubuntu Wheel

on:
  push:
  schedule:
    - cron: "32 */3 * * *"

jobs:
  build-wheel:
    name: Build wheel
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Maximize build space
        run: python python/setup.py
